### ISSUE TITLE
Replace app_dirs crate?

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/tealdeer#93]
The `app_dirs` crate has a negative `crev` review:

```
cargo crev repo query review app_dirs
---
kind: package review
version: -1
date: "2019-01-06T15:49:21.839825922-08:00"
from:
  id-type: crev
  id: FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE
  url: "https://github.com/dpc/crev-proofs"
package:
  source: "https://crates.io"
  name: app_dirs
  version: 1.2.1
  digest: mWo2YhBk4cw2sAuMAtQQukncheMihw0EDklVz6nqQGs
review:
  thoroughness: none
  understanding: none
  rating: negative
comment: |-
  It looks like it's not maintained, and they are problems with it. See https://github.com/dpc/crev/pull/133
```

In https://github.com/crev-dev/cargo-crev/pull/133 they migrated to the `directories` crate. Maybe tealdeer should do this too.
